name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: android-30
          sdk-build-tools: 30.0.1
          ndk-version: '21.4.7075529'  # Совместимая версия для armeabi-v7a
          cmake-version: '3.10.2'

      - name: Configure Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICES_JSON }}" > app/google-services.json
          chmod +x gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDebug
          ls -la app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 3

      - name: Upload mapping file
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: mapping-files
          path: app/build/outputs/mapping/
          retention-days: 7
