name: Android Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: actions/setup-android@v3
        with:
          android-sdk-file: 'commandlinetools-linux-8512546_latest.zip'

      - name: Accept licenses
        run: |
          yes | sdkmanager --licenses
          sdkmanager "platforms;android-30" "build-tools;30.0.1" "platform-tools" "ndk;21.4.7075529"

      - name: Configure Firebase
        run: |
          echo "${{ secrets.FIREBASE_SERVICES_JSON }}" > app/google-services.json
          chmod +x gradlew

      - name: Build APK
        run: |
          ./gradlew assembleDebug
          ls -la app/build/outputs/apk/debug/

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: game-app-debug
          path: app/build/outputs/apk/debug/*.apk
          retention-days: 3
